openshift/image-registry

Makefile, pkg/dockerregistry/server/app.go, pkg/dockerregistry/server/auth.go, pkg/dockerregistry/server/auth_test.go, pkg/dockerregistry/server/configuration/configuration.go, pkg/dockerregistry/server/quotarestrictedblobstore.go
=> Minor fixes and code cleanup

test/integration/v2/v2_docker_registry_test.go
=> Restore v2_docker_registry integration test

pkg/dockerregistry/server/auth.go, pkg/dockerregistry/server/auth/doc.go, pkg/dockerregistry/server/auth/token.go, pkg/dockerregistry/server/auth/token_test.go, pkg/dockerregistry/server/auth_test.go, pkg/dockerregistry/server/repository.go, pkg/dockerregistry/server/token.go, pkg/dockerregistry/server/util.go
Fix for RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1528613
=> Check resource name

pkg/dockerregistry/server/pullthroughblobstore.go, pkg/testframework/httptest.go, pkg/testframework/master.go, pkg/testframework/registry.go, test/integration/pullthrough/pullthrough_test.go, test/integration/pullthroughblob/pullthroughblob_test.go
=> Test for pullthrough

pkg/dockerregistry/server/configuration/configuration.go, pkg/dockerregistry/server/configuration/configuration_test.go
Fixes https://github.com/openshift/image-registry/issues/58
=> kube env variables has lower priority than configuration

hack/push-release.sh
=> Change the push strategy to match origin

pkg/dockerregistry/server/pullthroughmanifestservice.go, pkg/dockerregistry/server/pullthroughmanifestservice_test.go, pkg/dockerregistry/server/repository.go
fixes https://github.com/openshift/origin/issues/18292
=> don't attempt manifest pullthrough against internal registry

pkg/testframework/versions.go
fixes https://github.com/openshift/image-registry/issues/51
=> use versioned origin image for integration tests

pkg/dockerregistry/server/metrics/metrics.go
Increased metrics precision by replacing integer division by floating-point division.
SummaryVec replaced by HistogramVec, which allows aggregate metrics.
=> Fix metrics

pkg/dockerregistry/server/pullthroughblobstore.go, pkg/dockerregistry/server/pullthroughmanifestservice.go, pkg/dockerregistry/server/pullthroughmanifestservice_test.go, pkg/dockerregistry/server/repository.go
=> Background mirroring should use its own context for BlobStore

pkg/dockerregistry/server/app.go, pkg/dockerregistry/server/auth.go
Cluster role: https://github.com/openshift/origin/pull/18968
=> Use SAR request to verify metrics access

hack/lib/build/binaries.sh
fixes https://github.com/openshift/image-registry/issues/83
=> better golang version checking

pkg/dockerregistry/server/pullthroughmanifestservice.go, pkg/errors/errors.go, pkg/errors/handle.go, vendor/github.com/docker/distribution/registry/api/errcode/errors.go, vendor/github.com/docker/distribution/registry/handlers/app.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1578269.
<details>
<summary>Output of `docker pull 172.30.1.1:5000/myproject/foo` before patch</summary>
> Using default tag: latest
> Error response from daemon: error parsing HTTP 404 response body: json: cannot unmarshal number 727750330070774258508461169329606316441540384616086620444793670799490968006862819122321718201191797419997997401183211852380009717481319078856159647052207087382780934435083321402232281992602221429720237551009157906242822670434372156158838809966012277928394724347562504363760164573515974160075643611066621396686345711634830402036967312043372357208615635121399023173317333881066377186081786347073957563537028929133941922400310822439373446952424805314987188980795445055652506350160178856351642641065671487458569247708945840 …
=> Provide clients with additional information on failures

vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
bug https://bugzilla.redhat.com/show_bug.cgi?id=1587997
=> UPSTREAM: docker/distribution: 2605: s3: Add eu-west-3 region

pkg/imagestream/imagestreamhasblob.go
should improve https://bugzilla.redhat.com/show_bug.cgi?id=1589994
=> search tag events by tag before searching by age age

pkg/dockerregistry/server/tagservice.go, pkg/dockerregistry/server/tagservice_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1593795
=> Return 404 when image stream doesn't exist

pkg/testframework/master.go
An attempt to address https://github.com/openshift/test-infra/issues/164.
=> Fix waiting for cluster roles

test/integration/manifestmigration/manifestmigration_test.go, test/integration/offline/offline_test.go, test/internal/storage/waitable.go, test/internal/storagepath/storagepath.go
=> Add test for manifest migration

README.md
A link to the documentation describing what this is part of and how to get started would be useful.
~~The caveat is it will be out-of-date with each doc version release.~~ 
s/Promethus/Prometheus
=> README: add registry documentation link.

pkg/imagestream/imagestream.go
Fix panics from [bug 1639839](https://bugzilla.redhat.com/show_bug.cgi?id=1639839).
=> [3.9] Handle nil details

Dockerfile, Dockerfile.rhel7
Remove building with RPM in these images.  Changes already made to openshift/release
=> Add new Dockerfiles for centos and rhel7 that fit the standard shape

images/dockerregistry/Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1664853
=> [3.11] install rsync in docker-registry repo

images/dockerregistry/Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1614841
=> [3.10] install rsync in docker-registry repo

Dockerfile, Dockerfile.rhel7
https://bugzilla.redhat.com/show_bug.cgi?id=1664854
=> install rsync in docker-registry repo

cmd/dockerregistry/OWNERS, pkg/dockerregistry/OWNERS, tools/OWNERS
=> Clean owners

pkg/dockerregistry/server/app.go, pkg/imagestream/identifycandidaterepositories.go, pkg/imagestream/identifycandidaterepositories_test.go, pkg/imagestream/imagestream.go
=> prevent external hostname pullthrough + bump digest cache size

pkg/dockerregistry/server/pullthroughblobstore_test.go, pkg/dockerregistry/server/pullthroughmanifestservice.go, pkg/dockerregistry/server/pullthroughmanifestservice_test.go, pkg/dockerregistry/server/remoteblobgetter.go, pkg/dockerregistry/server/repository_test.go, pkg/dockerregistry/server/util.go, pkg/origin-common/image/registryclient/client.go, pkg/requesttrace/requesttrace.go, pkg/requesttrace/requesttrace_test.go, pkg/testframework/registry.go, test/integration/requestloop/requestloop_test.go
=> [3.11] Add request tracer to avoid loops

glide.lock, vendor/github.com/docker/distribution/registry/handlers/app.go, vendor/github.com/pkg/profile/.travis.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1655641
=> Bug 1655641: fix S3 health check when Bucket is empty

OWNERS
* Added @coreydaley as reviewer
=> Remove legionus as reviewer/approver

Makefile, hack/verify-govet.sh, test/integration/pullthroughblob/pullthroughblob_test.go
- Remove .travis.yml
- update make verify to remove gometalinter
- fix go vet to run on newer version
=> Bug 1740391: Update make verify for release-4.1

pkg/cmd/dockerregistry/dockerregistry.go
Running webserver in a separated go routine and awaiting for SIGTERM.
=> Bug 1710502: Implementing graceful shutdown.

pkg/dockerregistry/server/manifesthandler/manifestschema1handler.go, pkg/dockerregistry/server/manifesthandler/manifestschema2handler.go
This PR refers to https://bugzilla.redhat.com/show_bug.cgi?id=1745743.
We do a best effort here and retry when checking if a blob is present or
not. We need to do this as some of image registry storage backends have
eventual consistency and in some cases we may ended up checking for a
blob presence before it shows up.
This PR acts only on "manifest upload" as it tends to happen right
after the client uploaded blob layers. In the future we gonna need to
get rid of these retries, maybe by leveraging docker distribution redis
cache layer.
=> Bug 1745743: Implement retries when checking for blob presence.

Dockerfile, Dockerfile.rhel7
Not clearing the cache increased the image size by about 50M
=> Dockerfile: Clear yum cache after install

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go, vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go, vendor/modules.txt
Bump openshift/docker-distribution to get the recent VirtualHostedStyle update
=> bump openshift/docker-distribution

pkg/dockerregistry/server/metrics/metrics.go, pkg/dockerregistry/server/metrics/prometheus.go, pkg/dockerregistry/server/metrics/testing/counter.go, test/integration/metricspullthrough/metricspullthrough_test.go
Backport of #138 + update from 4.x
=> [release-3.11] Bug 1827744: Reduce cardinality of metrics, use summary instead of histograms

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go, vendor/modules.txt
Adding fix for invalid reference on s3 walk function.
https://github.com/openshift/docker-distribution/pull/21
=> Bug 1861304: Bump github.com/openshift/docker-distribution

pkg/testframework/registry.go
This PR adds a check on the external route for the ephemeral registry right after its deployment, this way we can assure the registry is accessible from outside the cluster prior to tests execution.
Networking team uses the following script to achieve the same on their tests:
https://github.com/openshift/origin/blob/master/test/extended/router/scoped.go#L241-L271
=> Bug 1905502: Polling route until registry is available

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go, vendor/modules.txt
New docker distribution project has an option to enable s3 requests
debug, bumping it so users can leverage it.
=> Bug 1924568: Bumping docker distribution dependency

pkg/dockerregistry/server/auth.go, pkg/dockerregistry/server/auth_test.go
SubjectAccessReview can be in one of three states: allowed, denied, and no opinion. Also it has the additional field EvaluationError that can indicate that some error occurred. The registry should log this information.
=> Better log message when action is not allowed

pkg/testframework/client.go
The current method is deprecated. The tests should use sha256 tokens that are recommended to use.
=> Bug 1960619: Use sha256 oauth tokens in tests

OWNERS
Remove `coreydaley` from reviewers list
=> Update OWNERS 

docs/how-to-deploy-dev-build.md
A brief manual on how to deploy a new development build for newcomers.
=> docs: How to deploy development build

.ci-operator.yaml, Dockerfile.rhel7, tools/gotest2junit/test/test_test.go
=> Use Go 1.17

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
=> Bug 2053222: Fix pull-through for images that have dots in their namespace

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
=> Bug 2053223: Fix pull-through for images that have dots in their namespace

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go, vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go, vendor/modules.txt
=> Bug 2053218: Fix pull-through for images that have dots in their namespace

pkg/dockerregistry/server/simplelookupicsp.go, pkg/dockerregistry/server/simplelookupicsp_test.go
=> Bug 2061785: Fix ICSP for subrepositories

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go, vendor/github.com/docker/distribution/vendor.conf, vendor/modules.txt
Vendors https://github.com/openshift/docker-distribution/pull/28.
Reverts #283.
=> Bug 2065689: Revert "Support authentication using gcp workload identity federation"

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go, vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go, vendor/github.com/docker/distribution/vendor.conf, vendor/modules.txt
=> Bug 2069807: Bug 2060362: Revert "Support authentication using gcp workload identity federation"

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go, vendor/github.com/docker/distribution/vendor.conf, vendor/modules.txt
Vendor changes from https://github.com/openshift/docker-distribution/pull/31.
=> Bug 2070791: Support authentication using gcp workload identity federation

go.mod, go.sum, vendor/github.com/docker/distribution/registry/storage/driver/gcs/gcs.go, vendor/github.com/docker/distribution/vendor.conf, vendor/modules.txt
Vendor changes from https://github.com/openshift/docker-distribution/pull/32.
=> Bug 2099416: Support authentication using gcp workload identity federation

OWNERS
this commits adds myself to the list of reviewers and approvers while also removes dmage (no longer part of the team).
=> NO-JIRA: chore: update owners file
