pkg/cmd/dockerregistry/dockerregistry.go
pkg/dockerregistry/server/blobdescriptorservice_test.go
pkg/dockerregistry/server/pullthroughblobstore_test.go
pkg/dockerregistry/testutil/manifests.go
pkg/dockerregistry/testutil/util.go
pkg/testframework/master.go
pkg/testframework/net.go
pkg/testframework/project.go
pkg/testframework/registry.go
test/integration/crossmount/crossmount_test.go
test/integration/imagelayers/imagelayers_test.go
test/integration/pullthrough/pullthrough_test.go
test/integration/v2/v2_docker_registry_test.go

Add integration test for cross-mounting blobs

---

pkg/cmd/dockerregistry/dockerregistry.go
pkg/version/doc.go
pkg/version/version.go

/assign @bparees 
Resolves #26

Add pkg/version

---

pkg/dockerregistry/server/configuration/configuration.go
pkg/dockerregistry/server/configuration/configuration_test.go

The docker/distribution has its own blobstater. All our middlewaries are ignored.
So when ServeBlob called, some of the storage requests will not go to our cache.

Fix performance regression

---

pkg/cmd/dockerregistry/dockerregistry.go
pkg/cmd/dockerregistry/listfs.go
pkg/cmd/dockerregistry/prune.go
pkg/cmd/dockerregistry/restore.go
pkg/dockerregistry/server/client/interfaces.go
pkg/dockerregistry/server/manifesthandler/doc.go
pkg/dockerregistry/server/manifesthandler/error.go
pkg/dockerregistry/server/manifesthandler/manifesthandler.go
pkg/dockerregistry/server/manifesthandler/manifestschema1handler.go
pkg/dockerregistry/server/manifesthandler/manifestschema2handler.go
pkg/dockerregistry/server/manifestservice.go
pkg/dockerregistry/server/prune/doc.go
pkg/dockerregistry/server/prune/prune.go
pkg/dockerregistry/server/prune/restore.go
pkg/dockerregistry/server/pullthroughmanifestservice.go
pkg/dockerregistry/server/storage/storage.go
pkg/dockerregistry/server/tagservice.go
pkg/imagestream/imagestream.go

[x] Find broken imagestream tags that reference non-existent objects in the storage.
[x] Find broken images that reference non-existent objects in the storage.
[x] Restore imagestream based on the storage data.
[x] Restore imagestream tag (not tagname) based on the storage data.
These options require:
```
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:default:registry
```

Add ability to verify and restore metadata

---

pkg/imagestream/imagestream.go

When the image stream becomes large enough that we cannot add any new records into it, the returned error "etcdserver: request is too large" has the nil value in the Details field.

Handle errors without Details

---

Makefile
pkg/testframework/master.go
test/integration/crossmount/crossmount_test.go
test/integration/offline/offline_test.go
test/integration/pullthroughblob/pullthroughblob_test.go

Uses the provided administrator kubeconfig and runs the tests against
that master. This allows the integration tests to be run against a stock
"openshift start master".
Another change in the master will make local dev cases easier so allowed
registries doesn't have to be customized.
@bparees @legionus

Support TEST_KUBECONFIG for integration tests

---

vendor/github.com/docker/distribution/registry/storage/driver/inmemory/driver.go

According golang documentation [1]: no goroutine should expect to be
able to acquire a read lock until the initial read lock is released.
[1] https://golang.org/pkg/sync/#RWMutex

UPSTREAM: docker/distribution: 2599: Fix deadlock in the inmemory storage driver

---

vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go

Backport: https://github.com/openshift/image-registry/pull/94
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1587996

[3.9] UPSTREAM: docker/distribution: 2605: s3: Add eu-west-3 region

---

pkg/dockerregistry/server/app.go
pkg/dockerregistry/server/metrichandler.go
pkg/dockerregistry/server/metrics/cache.go
pkg/dockerregistry/server/metrics/metrics.go
pkg/dockerregistry/server/metrics/prometheus.go
pkg/dockerregistry/server/metrics/testing/counter.go
pkg/dockerregistry/server/metrics/timer.go
pkg/dockerregistry/server/pullthroughblobstore_test.go
pkg/dockerregistry/server/pullthroughmanifestservice.go
pkg/dockerregistry/server/pullthroughmanifestservice_test.go
pkg/dockerregistry/server/registry_test.go
pkg/dockerregistry/server/remoteblobgetter.go
pkg/dockerregistry/server/repository.go
pkg/dockerregistry/server/util.go
pkg/testframework/registry.go
test/integration/metricspullthrough/metricspullthrough_test.go
test/integration/pullthroughblob/pullthroughblob_test.go

https://trello.com/c/g3380oUO/1534-8-implement-recommended-registry-metrics-registry
New metrics:
* imageregistry_pullthrough_blobstore_cache_requests_total{type}
* imageregistry_pullthrough_repository_duration_seconds_bucket{registry,operation,le}
* imageregistry_pullthrough_repository_duration_seconds_sum{registry,operation}
* imageregistry_pullthrough_repository_duration_seconds_count{registry,operation}
* imageregistry_pullthrough_repository_errors_total{registry,operation,code}
Cache request types:
* Hit
* Miss
Repository operations:
* Init
* BlobStore.Stat
* BlobStore.Open
* ManifestService.Get

Add pullthrough metrics

---

pkg/dockerregistry/server/blobdescriptorservice.go
pkg/dockerregistry/server/configuration/configuration.go
pkg/dockerregistry/server/registry_test.go
pkg/dockerregistry/server/repository.go
pkg/dockerregistry/server/repository_test.go
pkg/dockerregistry/server/tagservice.go
pkg/dockerregistry/server/tagservice_test.go
pkg/imagestream/imagestream.go
pkg/imagestream/imagestreamhasblob.go

> I’m not sure pullthrough enabled false is something we should support. In 8 release we’ve never had a reason to trn it off. (c) Clayton Coleman
https://github.com/openshift/origin/pull/19969#discussion_r195331219
https://github.com/openshift/image-registry/pull/101#discussion_r195322187
/cc @smarterclayton

pullthrough is not optional

---

pkg/dockerregistry/server/app.go
pkg/dockerregistry/server/metrics/metrics.go
pkg/dockerregistry/server/metrics/prometheus.go
pkg/dockerregistry/server/metrics/testing/counter.go
pkg/dockerregistry/server/wrapped/filewriter.go
pkg/dockerregistry/server/wrapped/readcloser.go
pkg/dockerregistry/server/wrapped/storagedriver.go
pkg/dockerregistry/server/wrapped/wrapper.go
pkg/dockerregistry/server/wrapped/wrapper_test.go
test/integration/metricspullthrough/metricspullthrough_test.go

https://trello.com/c/g3380oUO/1534-8-implement-recommended-registry-metrics-registry
New metrics:
* imageregistry_storage_duration_seconds_bucket{operation,le}
* imageregistry_storage_duration_seconds_sum{operation}
* imageregistry_storage_duration_seconds_count{operation}
* imageregistry_storage_errors_total{operation,code}

Add metrics for the storage subsystem

---

pkg/dockerregistry/server/app.go
pkg/dockerregistry/server/auth.go
pkg/dockerregistry/server/catalog.go
pkg/dockerregistry/server/catalog_test.go
pkg/dockerregistry/server/registry.go
pkg/dockerregistry/server/registry_test.go
pkg/testutil/fakeopenshift.go

Implements the upstream repository catalog API call:
GET /v2/_catalog
Returned is a list of repository names as json:
200 OK
Content-Type: application/json
{ "repositories": [ <name>, ... ] }
Pagination is supported by mapping the last returned repository name to an opaque continue token received from master API and using it on the next invocation.
Task: https://trello.com/c/AZINw5qI
Associated origin PR to allow registry to list image stream: openshift/origin#19879
Documentation: https://github.com/openshift/openshift-docs/pull/10102
**TODO:**

Registry catalog

---

pkg/dockerregistry/server/app.go
pkg/dockerregistry/server/cache/cacheprovider.go
pkg/dockerregistry/server/cache/cacheprovider_test.go
pkg/dockerregistry/server/configuration/configuration.go
pkg/dockerregistry/server/supermiddleware/app.go
pkg/dockerregistry/server/supermiddleware/app_test.go
vendor/github.com/docker/distribution/registry/handlers/app.go
vendor/github.com/docker/distribution/registry/storage/cache/provider/cacheprovider.go

New cache provider should join our cache and `docker/distribution` cache in one. The expiration time  now affects it. Also we can prune it.

Cache provider

---

.travis.yml
hack/lib/constants.sh
hack/test-local-registry.sh
pkg/dockerregistry/server/blobdescriptorservice.go
pkg/dockerregistry/server/client/interfaces.go
pkg/dockerregistry/server/repository_test.go
pkg/dockerregistry/server/util.go
pkg/imagestream/cachedimagestreamgetter.go
pkg/imagestream/imagestream.go
pkg/imagestream/imagestreamhasblob.go
pkg/testutil/fakeopenshift.go

Using the new imagestream/layers API, avoid making O(N) image fetches in the case where we don't have a cached association for the reference.
API in https://github.com/openshift/origin/pull/19969

Perform an O(1) check to find layers in an image

---

pkg/dockerregistry/server/metrics/metrics.go
pkg/dockerregistry/server/metrics/prometheus.go
pkg/dockerregistry/server/metrics/testing/counter.go
test/integration/metricspullthrough/metricspullthrough_test.go

The repo latency metrics could have extremely high cardinality, so without
a definite use case let's remove it. Instead of Histograms, use Summaries
which simplify buckets and make visualization easier.

Reduce cardinality of metrics, use summary instead of histograms

---

pkg/testframework/client.go

This field will be required in 4.x
@bparees

Update OAuthClient to include GrantMethod

---

pkg/testframework/client.go

`Scopes` and `RedirectURI` will be required once https://github.com/openshift/origin/pull/22697 lands.

Update test OAuthAccessToken with required fields

---

pkg/imagestream/imagestream.go

currently prints wrong value in the warning

Fix Warning Log Message

---

Makefile
pkg/testframework/httptest.go
pkg/testframework/master.go
pkg/testframework/net.go
pkg/testutil/util.go
tools/import-verifier/import-verifier.go

gosec does static code analysis and checks for common security issues in golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile.

Introduce gosec for security checks

---

Makefile

We are disabling this tool for now. With **gosec** our tests are constantly failing and that is delaying us of getting what has been planned for the sprint done. We will revisit this in the future and there is already a ticket in place to do so.
Regarding the four security flaws reported by **gosec** on this repo:
1. Three of them are not critical(using variables when "shelling out" commands)
2. One of them is related to the fact we have profiling(pprof) enabled on the registry.
For item number 1 I have checked and the variables being used when shelling out won't cause any problem as the user can't tamper with them. As for the second, to have profiling enabled is mandatory, further checks for alternatives could be done when we start working on it.
For reference, the ticket is …

Disabled gosec.

---

pkg/dockerregistry/server/prune/prune.go

In some cases we have some images on the blob storage that contain names
considered to be invalid by the ImageStream API. Names containing / or
even % are not considered valid for Images.
As some customers are not able to prune their images due to this error
this patch adds a check and sets the image to be pruned if it contains
an invalid name(they should not be there anyways).

Bug 1749256: Checking if image name is valid, prune otherwise.

---

pkg/dockerregistry/server/pullthroughblobstore.go

`%#v` is supposed to provide more detailed information about the problem, but in practice `%#v` makes some error message unusable, for example:
> msg="unable to find blob \\"sha256:7ddcb796f98af1e76313d7655000413483316d2f1cf8dbbda75b8bcb75226405\\": driver.Error{DriverName:\\"swift\\", Enclosed:(*url.Error)(0xc00093b590)}"

Don't use Go-syntax representation for errors

---

pkg/imagestream/imagestream.go

It is not an error for PublicDockerImageRepository to be set empty
to an image stream (it means the registry is not exposed by default).

Bug 1827672: Only warn if PublicDockerImageRepository is set

---

pkg/dockerregistry/server/manifestservice.go
pkg/dockerregistry/server/pullthroughmanifestservice.go
pkg/dockerregistry/server/remoteblobgetter.go
pkg/errors/errors.go
pkg/errors/errors_test.go
pkg/imagestream/cachedimagestreamgetter.go
pkg/imagestream/image.go
pkg/imagestream/imagestream.go
pkg/testutil/fakeopenshift.go

This is a refactoring PR and has two changes:
1. remove legacy checks (support of OpenShift 3.6 and below)
2. make errors.Error an interface

Bug 1815562: refactor errors package

---

Dockerfile.rhel7

Updating openshift-enterprise-registry builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-registry.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating openshift-enterprise-registry builder & base images to be consistent with ART

---

go.mod
pkg/dockerregistry/server/manifesthandler/manifesthandler.go
pkg/dockerregistry/server/manifesthandler/manifestocihandler.go
pkg/testutil/manifests.go
test/integration/oci/oci_test.go

This patch adds support for OCI schema into the internal registry. OCI
schemas are very similar to Docker schema v2 thus this patch only
creates a new manifest handler (very similar to docker schema v2
handler) and register it as a known schema handler.

IR-114: Adding support for OCI schema

---

go.mod
go.sum
vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go
vendor/modules.txt

This allows setting REGISTRY_STORAGE_S3_CREDENTIALSCONFIGPATH to point to a file containing AWS credentials (instead of setting environment variables containing the credentials).
The registry operator can now chose to mount a Secret/ConfigMap containing an AWS credentials configuration file which should allow using AWS authentication methods besides the (still supported) AWS access and secret keys.

Bug 1921909: vendor in updated openshift/docker-distribution

---

pkg/dockerregistry/server/auth.go
pkg/dockerregistry/server/auth_test.go

Modified challenges for token involved errors with appropriate error from [distribution code](https://github.com/distribution/distribution/blob/main/registry/client/errors.go#L109-L113), so access denied error would cause appropriate error logs.

Bug 1902456: Fixed incorrect access denied error logs

---

pkg/dockerregistry/server/auth.go
pkg/dockerregistry/server/auth_test.go

This reverts commit 6f3403fd190a507d56bee1dd59afff5b1779eece. We are seeing errors pulling from the image registry on 4.10 when pulling anonymously.  There's only 24 commits between 4.9 and 4.10 and this seemed to be most obvious one.
Results of this patch applied confirm it fixes our issue:
https://gist.github.com/deads2k/079bf414a001ace522da935ac55e26e6

Bug 2060605: Revert "Fixed incorrect access denied error logs"

---

pkg/dockerregistry/server/pullthroughblobstore.go
pkg/dockerregistry/server/pullthroughmanifestservice.go
pkg/dockerregistry/server/remoteblobgetter.go

makes the registry forward http.StatusTooManyRequests back
to the client during pullthrough operations.

Bug 1923536: forward http.StatusTooManyRequests to client

---

vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go

Taken from https://github.com/prometheus/client_golang/pull/987
and manually applied to relevant files.

Bug 2067893: apply upstream prometheus/client_golang fix

---

pkg/testframework/registry.go

The new default pod security policy in OCP is very restrictive and it requires security contexts to have proper values.
Fixes CI failures like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_image-registry/341/pull-ci-openshift-image-registry-master-e2e-agnostic-image-registry/1560248522756853760

Fix security context for test pods

---

pkg/dockerregistry/server/simplelookupicsp.go
pkg/dockerregistry/server/simplelookupicsp_test.go
test/integration/pullthrough/pullthrough_test.go

Backport: https://github.com/openshift/image-registry/pull/377 
Allow ICSP IDMS coexisting

[release-4.14] OCPBUGS-22826: Allow ICSP IDMS coexisting

---

pkg/dockerregistry/server/metrics/errorcodes.go
pkg/dockerregistry/server/metrics/metrics.go

before this change, "read-only file system" errors would show up in the metrics as "UNKNOWN".
this commit inspects the enclosed storage path error and reports a metric reporting the failed operation.
---
The below steps have been tested against `4.18.0-0.test-2024-09-26-122820-ci-ln-0y1k6pk-latest` on AWS.
Easiest way I could find to achieve this is to configure the registry to use a pvc, then edit the image-registry deployment to mount the pvc with `readOnly: true`.
**Set project to openshift-image-registry**
```
oc project openshift-image-registry
```
**Create the PVC**
```
cat << EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: image-registry-test-claim
namespace: openshift-image-registry
spec:
accessModes:
- ReadWriteOnce
resources:
requests: …
```

IR-489: export storage read-only errors as metrics

---

go.mod
go.sum
vendor/github.com/distribution/distribution/v3/registry/storage/driver/s3-aws/s3.go
vendor/modules.txt

bumping docker-distribution dependency as the new version includes a few new regions.
this bump also includes the changes introduced by
https://github.com/openshift/docker-distribution/pull/44.

OCPBUGS-38874,OCPBUGS-25981: bump docker-distribution to add new regions

---

go.mod
go.sum
vendor/github.com/distribution/distribution/v3/registry/storage/driver/s3-aws/s3.go
vendor/modules.txt

bumping docker-distribution dependency as the new version includes a few new regions.

[release-4.18] OCPBUGS-49693: bump docker distribution

---

go.mod
go.sum
vendor/github.com/distribution/distribution/v3/registry/storage/driver/s3-aws/s3.go
vendor/modules.txt

bumping docker-distribution dependency as the new version includes a few new regions.

[release-4.17] OCPBUGS-49695: bump docker distribution

---

go.mod
go.sum
vendor/github.com/distribution/distribution/v3/registry/storage/driver/s3-aws/s3.go
vendor/modules.txt

disable the artificial aws region check. we are doing this so we can support new aws regions without requiring patching the code every time.
this is a test and should not land on main.

IR-522: disable aws region check

---

go.mod
go.sum
vendor/github.com/distribution/distribution/v3/registry/storage/driver/s3-aws/s3.go
vendor/modules.txt

Depends on https://github.com/openshift/docker-distribution/pull/61

[release-4.17] OCPBUGS-60090: bump docker distribution to fix purgeuploads panic
